export const elements = {
  loadingSection: document.getElementById("loadingSection"),
  loadingMessage: document.getElementById("loadingMessage"),
  authSection: document.getElementById("authSection"),
  todoPanel: document.getElementById("todoPanel"),
  registerForm: document.getElementById("registerForm"),
  loginForm: document.getElementById("loginForm"),
  showRegisterBtn: document.getElementById("showRegisterBtn"),
  showLoginBtn: document.getElementById("showLoginBtn"),
  doRegisterBtn: document.getElementById("doRegisterBtn"),
  doLoginBtn: document.getElementById("doLoginBtn"),
  logoutBtn: document.getElementById("logoutBtn"),
  createTodoBtn: document.getElementById("createTodoBtn"),
  newTaskInput: document.getElementById("newTaskInput"),
  todoListContainer: document.getElementById("todoListContainer"),
  authMessage: document.getElementById("authMessage"),
  todoMessage: document.getElementById("todoMessage"),
  userGreeting: document.getElementById("userGreeting"),
  sessionExpiryModal: document.getElementById("sessionExpiryModal"),
  sessionLogoutBtn: document.getElementById("sessionLogoutBtn"),
  sessionReloginBtn: document.getElementById("sessionReloginBtn"),
  regUsername: document.getElementById("regUsername"),
  regEmail: document.getElementById("regEmail"),
  regPassword: document.getElementById("regPassword"),
  loginUsername: document.getElementById("loginUsername"),
  loginPassword: document.getElementById("loginPassword")
};
